version: '3'

services:
  app:
    build: .
    command: yarn dev
    restart: unless-stopped
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    container_name: database_node
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_DATABASE: PROTOTYPE_DATABASE
    ports:
      - '3308:3306'
